#!/usr/bin/env bash
set -e

# Feature test: verify the Podman remote client is installed and on the PATH.
# The autogenerated path runs without the host-socket bind mount, so only the
# CLI presence is asserted here (the mount is host-specific and exercised when
# the feature is consumed).
source dev-container-features-test-lib

check "podman binary exists" command -v podman
check "podman --version works" podman --version

reportResults
