#!/usr/bin/env bash
set -euo pipefail

# Feature test: verify the Podman remote client is installed and on the PATH.
# The autogenerated path runs without the host-socket bind mount, so only the
# CLI presence is asserted here (the mount is host-specific and exercised when
# the feature is consumed).
source dev-container-features-test-lib

check "podman binary exists" command -v podman
check "podman binary is executable" test -x "$(command -v podman)"
check "podman --version works" podman --version
check "CONTAINER_HOST is set" test -n "${CONTAINER_HOST:-}"
check "CONTAINER_HOST points to /tmp/podman.sock" test "${CONTAINER_HOST:-}" = "unix:///tmp/podman.sock"

reportResults
