#!/usr/bin/env bash
set -euo pipefail

# Scenario test: verify ~/.claude symlinks into the mounted volume. This
# scenario supplies the named volume so the symlink can be asserted (the
# autogenerated test runs without mounts and only checks the dir exists).
source dev-container-features-test-lib

check "~/.claude is a symlink" test -L "$HOME/.claude"
check "~/.claude symlinks to /mnt/claude-cache" test "$(readlink "$HOME/.claude")" = "/mnt/claude-cache"
check "~/.claude is writable through the symlink" test -w "$HOME/.claude"

reportResults
