#!/bin/bash
set -e

# Scenario test: verify ~/.claude symlinks into the mounted volume. This
# scenario supplies the named volume so the symlink can be asserted (the
# autogenerated test runs without mounts and only checks the dir exists).
source dev-container-features-test-lib

if [ -L "$HOME/.claude" ]; then
    check "~/.claude is a symlink into the claude-cache volume" test "$(readlink "$HOME/.claude")" = "/mnt/claude-cache"
else
    check "~/.claude directory exists" test -d "$HOME/.claude"
fi

reportResults
