#!/usr/bin/env bash
set -euo pipefail

# Scenario test: verify OpenCode's XDG data/config dirs are symlinked into the
# mounted volumes. Unlike the autogenerated test (which runs without mounts),
# this scenario supplies the named volumes so the symlink paths can be asserted.
source dev-container-features-test-lib

data_dir="${XDG_DATA_HOME:-$HOME/.local/share}/opencode"
config_dir="${XDG_CONFIG_HOME:-$HOME/.config}/opencode"

check "data dir is a symlink" test -L "$data_dir"
check "data dir symlinks to /mnt/opencode-data" test "$(readlink "$data_dir")" = "/mnt/opencode-data"
check "data dir is writable through the symlink" test -w "$data_dir"

check "config dir is a symlink" test -L "$config_dir"
check "config dir symlinks to /mnt/opencode-config" test "$(readlink "$config_dir")" = "/mnt/opencode-config"
check "config dir is writable through the symlink" test -w "$config_dir"

reportResults
