#!/usr/bin/env bash
set -euo pipefail

# Feature test: verify xdg-utils is installed and the xdg-open wrapper is in place.
# The autogenerated path runs without the host browser pipe bind mount, so only
# the wrapper presence and the fallback path are asserted here.
source dev-container-features-test-lib

check "xdg-utils package installed" dpkg -s xdg-utils
check "xdg-open wrapper exists" test -x /usr/local/bin/xdg-open
check "wrapper is ours (not /usr/bin/xdg-open)" test "$(command -v xdg-open)" = "/usr/local/bin/xdg-open"

# Negative test: when no host browser pipe exists, the wrapper must fall back
# to /usr/bin/xdg-open. We verify the wrapper contains the fallback logic.
check "wrapper has fallback to /usr/bin/xdg-open" grep -q "/usr/bin/xdg-open" /usr/local/bin/xdg-open
check "wrapper checks for pipe existence" grep -q '\-p ' /usr/local/bin/xdg-open

reportResults
