#!/usr/bin/env bash
set -e

# Feature test: verify xdg-utils is installed and the xdg-open wrapper is in place.
# The autogenerated path runs without the host browser pipe bind mount, so only
# the wrapper presence and the fallback path are asserted here.
source dev-container-features-test-lib

check "xdg-utils package installed" dpkg -s xdg-utils
check "xdg-open wrapper exists" test -x /usr/local/bin/xdg-open
check "wrapper is ours (not /usr/bin/xdg-open)" test "$(command -v xdg-open)" = "/usr/local/bin/xdg-open"

reportResults